spring.application.name=diaetologen-BE
spring.datasource.url=jdbc:postgresql://localhost:5433/diet
spring.datasource.username=postgres
spring.datasource.password=0101

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081
spring.jpa.open-in-view=false

# Google Gemini API Configuration
groq.api.key=$env:GROQ_API_KEY
groq.model=llama-3.1-8b-instant